module.exports = {
  apps: [
    {
      name: 'ai-tg-bot',
      script: 'src/bot/index.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_memory_restart: '500M',
      env: { NODE_ENV: 'production' },
      error_file: 'logs/bot-err.log',
      out_file: 'logs/bot-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'ai-tg-site',
      script: 'src/site/index.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_memory_restart: '300M',
      env: { NODE_ENV: 'production' },
      error_file: 'logs/site-err.log',
      out_file: 'logs/site-out.log',
      merge_logs: true,
      time: true,
    },
  ],
};
